spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://127.0.0.1:7003
    
server:
  port: 8082

eureka:
  client:
    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://register1:8761/eureka/, http://register2:8762/eureka/
      
feign:
  hystrix:
    enabled: true
    
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  
hystrix:
  command:
    "FeignServiceClient#home(String)":
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            interruptOnCancel: true
      circuitBreaker:
        requestVolumeThreshold: 10
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000