spring:
  application:
    name: service-feign
  zipkin:
      base-url: http://127.0.0.1:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
    
server:
  port: 8082

eureka:
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
    hostname: localhost
#    prefer-ip-address: true
#    ipAddress: 127.0.0.2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://register1:8761/eureka/, http://register2:8762/eureka/
    healthcheck:
      enabled: true
      
feign:
  hystrix:
    enabled: true
    
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false

hystrix:
  command:
    "FeignServiceClient#home(String)":
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            interruptOnCancel: true
      circuitBreaker:
        requestVolumeThreshold: 10
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
logging:
  file: d:/log/feign.log