server:
  port: 7002
  
spring:
  application:
    name: monitor

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
turbine:
  app-config: service-ribbon,service-feign
  cluster-name-expression: new String("default")
  combine-host-port: true