server:
  port: 7002
  
spring:
  application:
    name: monitor

eureka:
  instance:
    # 续约更新时间间隔（单位秒，默认30秒）
    lease-expiration-duration-in-seconds: 10
    # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 10
    #以IP地址注册到服务中心，相互注册使用IP地址
    preferIpAddress: true
    #强制指定IP地址，默认会获取本机的IP地址
#    ipAddress: 127.0.0.2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://register1:8761/eureka/, http://register2:8762/eureka/
    # 健康检查
    healthcheck:
      enabled: true

turbine:
  instanceUrlSuffix:
    default: /hystrix.stream
  app-config: service-ribbon,service-feign
  cluster-name-expression: new String("default")
  combine-host-port: true