spring:
  application:
    name: service-ribbon
  zipkin:
    base-url: http://127.0.0.1:7003
    
server:
  port: 8081

eureka:
  client:
    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://register1:8761/eureka/, http://register2:8762/eureka/
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  config:
    stream:
      maxConcurrentConnections: 50