spring:
# git管理配置
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/JohnWei1993/SpringCloud/
#          searchPaths: config-repo/
#          label: master
#          username: JohnWei1993
#          password: hswsq1993
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/dev
  profiles:
    active: native
  application:
    name: config-server
    
server:
  port: 7001
  